package(default_visibility = ["//visibility:public"])

config_setting(
    name = "selenium_480",
    define_values = {
        "selenium_version": "4.8.0",
    }
)

config_setting(
    name = "selenium_400",
    define_values = {
        "selenium_version": "4.0.0",
    },
)

config_setting(
    name = "chrome_driver_109",
    define_values = {
        "chrome_version": "109",
    },
)

config_setting(
    name = "chrome_driver_110",
    define_values = {
        "chrome_version": "110",
    },
)

config_setting(
    name = "chrome_driver_111",
    define_values = {
        "chrome_version": "111",
    }
)


