package(default_visibility = ["//visibility:public"])

py_library(
    name = "chatgpt",
    srcs = [
        "chatgpt.py",
    ],
    deps = [
        "//utils:utils",
        "//proto:config_proto",
    ],
)
