package(default_visibility = ["//visibility:public"])

py_library(
    name = "file_utils",
    srcs = ["file_utils.py"],
    deps = [
        "@com_google_protobuf//:protobuf_python",
    ],
)

py_library(
    name = "utils",
    srcs = ["utils.py"],
)
