package(default_visibility = ["//visibility:public"])

py_binary(
    name = "selenium_wechat",
    srcs = [
        "selenium_wechat.py",
    ],
    deps = [
        "//chatgpt:chatgpt",
        "@selenium_py//:selenium",
    ],
)
